version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      

  ml:
    build:
      context: ./ml
    ports:
      - "5000:5000"
    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      
